import './js/header';
import './js/hero';
import './js/reviewsme';
import './js/benefits';
import './js/projects';
import './js/faq';
import './js/covers';
import './js/reviews';
import './js/work-together';
